# -*- coding: utf-8 -*-
"""Sprint3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L-n06kz_c0SfXMf-ZKeb4Spedi_7iuKg

Instalando o DNSPython
"""

!pip install dnspython

exit()

#Importando Bibliotecas
import pandas as pd
from pandas import DataFrame

#Lendo CSV
dados_normal = pd.read_csv('FluxoNormal - FluxoNormal.csv')
dados_Um_Furo = pd.read_csv('FluxoUmFuro - FluxoUmFuro.csv')
dados_Dois_Furos = pd.read_csv('FluxoDoisFuros - FluxoDoisFuros.csv')

#Convertendo para Dicionarios 
dados_normal_to_dict = dados_normal.to_dict(orient= "records")
dados_Um_Furo_to_dict = dados_Um_Furo.to_dict(orient= "records")
dados_Dois_Furos_to_dict = dados_Dois_Furos.to_dict(orient= "records")

print(dados_normal_to_dict)  
print(dados_Um_Furo_to_dict)  
print(dados_Dois_Furos_to_dict)

import datetime      # Imports datetime library
import pymongo     # Importando a Biblioteca do Mongol 
from pymongo import MongoClient   # Importação Da biblioteca MongoClient
import json 
# Adicionando a URL do MongoDb
uri = 'mongodb+srv://LJGT:ifbedu@cluster0.fostvjg.mongodb.net/?retryWrites=true&w=majority'

# Iniciando a Conexão dos clientes ao servidor MongoDB  
client = MongoClient( uri )

# Criando o BD
BancodeDados= client["Controle_de_Fluxo"] 

# Criando Colecao 
colecao_Normal = BancodeDados["Fluxo_Normal"]
colecao_Um_Furo = BancodeDados["Fluxo_Um_Furo"]
colecao_Dois_Furos = BancodeDados["Fluxo_Dois_Furos"]

#Adicionando dados Convertidos na Coleção 
colecao_Normal_adicionada = colecao_Normal.insert_many(dados_normal_to_dict)
colecao_Um_Furo_adicionadas = colecao_Um_Furo.insert_many(dados_Um_Furo_to_dict)
colecao_Dois_Furosadicionadas = colecao_Dois_Furos.insert_many(dados_Dois_Furos_to_dict)
print(colecao_Normal_adicionada.inserted_ids)
print(colecao_Um_Furo_adicionadas .inserted_ids)
print(colecao_Dois_Furosadicionadas.inserted_ids)

#Teste de Conexão
BancodeDados.stats

#Listando as Coleções do Banco de dados
print(BancodeDados.list_collection_names())
#colecao.drop()